### ISSUE TITLE
simdock looks for mychips main directory in a case-sensitive way

### ISSUE THREAD

**Issue by michielbdejong** [gotchoices/MyCHIPs#131]
I found that when running this on GitPod, I had to rename `/workspace/MyCHIPS` to `/workspace/mychips`:
```
gitpod /workspace/MyCHIPs/test/sim (master) $ ./simdock 
Can't find mychips main directory
gitpod /workspace/MyCHIPs/test/sim (master) $ cd ../../..
gitpod /workspace $ mv MyCHIPs mychips
gitpod /workspace $ cd mychips/test/sim/
gitpod /workspace/mychips/test/sim (master) $ ./simdock 
Error response from daemon: No such container: devel
[...[
```

due to the check in https://github.com/gotchoices/MyCHIPs/blob/908fb5c/test/sim/simdock#L41 being case-sensitive.

But when you run `git clone https://github.com/gotchoices/MyCHIPs` it will create the mixed-case directory name.

**Comment by gotchoices** [comment]
I think this has been fixed in recent dev branch commits
